config/routes.rb
Rails.application.routes.draw do
  root 'bootstrap_examples#index'
  get "/navbar", to: 'bootstrap_examples#navbar'
  get "/btn", to: 'bootstrap_examples#btn'
  get "/grid", to: 'bootstrap_examples#grid'
  get "/table", to: 'bootstrap_examples#table'
  get "/tmp", to: 'bootstrap_examples#tmp'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bootstrap_examples_controller.rb
class BootstrapExamplesController < ApplicationController
  def index
  end

  def navbar
  end

  def btn
  end

  def grid
  end

  def table
  end

  def tmp
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def oss_url(file)
    github_url(file)
  end

  def github_url(file)
    "https://github.com/vochicong/bootstrap4-haml-rails/blob/master/" + file
  end
end

app/helpers/bootstrap_examples_helper.rb
module BootstrapExamplesHelper
end

app/views/bootstrap_examples/btn.html.haml
%h1 Awesome buttons

.m-2
  %a.btn.btn-outline-primary{ href: "#", role: "button" } Primary
  %a.btn.btn-secondary{ href: "#", role: "button" } Secondary
  %a.btn.btn-success{ href: "#", role: "button" } Success
  %a.btn.btn-info{ href: "#", role: "button" } Info
  %a.btn.btn-warning{ href: "#", role: "button" } Warning
  %a.btn.btn-danger{ href: "#", role: "button" } Danger
  %a.btn.btn-link{ href: "#", role: "button" } Link

.m-2
  %a.btn.btn-primary.btn-block{ href: "#", role: "button" } Block level button

.m-2
  %a.btn.btn-primary.btn-lg{ href: "#", role: "button" } Large button
  %a.btn.btn-primary.btn-sm{ href: "#", role: "button" } Small button

.m-2
  %button.btn.btn-primary{ type: "button", "data-toggle": "button", "aria-pressed": "false" } Inactive
  %button.btn.btn-primary.active{ type: "button", "data-toggle": "button", "aria-pressed": "true" } Active
  %a.btn.btn-primary.disabled{ href: "#", role: "button", "aria-disabled": "true" } Disabled

.m-2
  .btn-group{ "data-toggle": "buttons" }
    %label.btn.btn-primary.active
      %input{ type: "checkbox", checked: true } Checkbox 1
    %label.btn.btn-primary.active
      %input{ type: "checkbox", checked: true } Checkbox 2
    %label.btn.btn-primary
      %input{ type: "checkbox" } Checkbox 3

.m-2
  .btn-group{ "data-toggle": "buttons" }
    %label.btn.btn-primary.active
      %input{ type: "radio", name: "options", id: "option1", checked: true } Radio 1
    %label.btn.btn-primary
      %input{ type: "radio", name: "options", id: "option2" } Radio 2
    %label.btn.btn-primary
      %input{ type: "radio", name: "options", id: "option3" } Radio 3

%h2 Source code:
%ul.list-group
  %li.list-group-item
    = link_to "btn.html.haml", oss_url("app/views/bootstrap_examples/btn.html.haml")

%h2 References:
%ul.list-group
  %li.list-group-item
    %a{href:"https://v4-alpha.getbootstrap.com/components/buttons/"} Bootstrap/Components/Buttons

app/views/bootstrap_examples/grid.html.haml
%h1 Grid

.lead Bootstrap includes a powerful mobile-first flexbox grid system for building layouts of all shapes and sizes.

.row
  .col Entire row
.row
  .col 1st of 2
  .col 2nd of 2
.row
  .col 1st of 3
  .col 2nd of 3
  .col 3rd of 3
.row
  .col.col-2
    %code.highlighter-rouge .col-2 2/12
  .col.col-3
    %code.highlighter-rouge .col-5 3/12
  .col Auto (=5/12)
.row
  .col.col-md-3.hidden-sm-down
    %code.highlighter-rouge .col-md-3 .hidden-sm-down
  .col.col-md-6.col-sm-12
    %code.highlighter-rouge .col-md-6 .col-sm-12
  .col.hidden-sm-down
    %code.highlighter-rouge .hidden-sm-down

// Mix collumn widths for various device sizes
.row
  .col.col-md-8 .col.col-md-8 66% width for >md
  .col.col-md-4 .col.col-md-4
.row
  .col-6.col-md-4 .col-6.col-md-4 33% with for >md
  .col-6.col-md-4 .col-6.col-md-4
  .col-6.col-md-4 .col-6.col-md-4

// Alignment
.bd-example-row-flex-cols
  .row.align-items-start .row.align-items-start
  .row.align-items-center .row.align-items-center
  .row.align-items-end .row.align-items-end
  .row
    .col.align-self-end .col.align-self-end
    .col.align-self-center  .col.align-self-center
    .col.align-self-start .col.align-self-start

%h2 Source code
%ul
  %li
    %a{ href: "#{oss_url('app/views/bootstrap_examples/grid.html.haml')}" } grid.html.haml

%h2 References
%ul
  %li
    %a{ href: "https://v4-alpha.getbootstrap.com/layout/grid/" } Grid system
  %li
    %a{ href: "https://v4-alpha.getbootstrap.com/layout/responsive-utilities/" } Responsive utilities

app/views/bootstrap_examples/index.html.haml
%h1 Bootstrap4/Rails

.lead Some Bootstrap 4 Example in Haml&Sass/Rails

Select an example from menu "Selection"

app/views/bootstrap_examples/navbar.html.haml
%h1 Navigation bar

.lead It is at the top.

%h2 Source code:
%ul.list-group
  %li.list-group-item
    = link_to "_navigation.html.haml", oss_url("app/views/layouts/_navigation.html.haml")
  %li.list-group-item
    = link_to "custom.scss", oss_url("app/assets/stylesheets/custom.scss")
  %li.list-group-item
    = link_to "application.js", oss_url("app/assets/javascripts/application.js")

app/views/bootstrap_examples/table.html.haml
%h1 Table

.lead 1st and 2nd rows are sticky. The others will scroll.
.lead 左の行は固定され、それ以外の行はスクロールされる。

.scroll-example
  %table.table.table-striped.table-bordered.table-hover
    - nrow = 20
    - ncol = 30
    %thead
      %tr.fixed-y0
        %th.fixed-x0 #
        %th.fixed-x1 TH1
        - (2..ncol).each do |j|
          %th TH#{j}
    %tbody
    - (1..nrow).each do |i|
      %tr
        %td.fixed-x0 #{i}
        %td.fixed-x1 td1
        - (2..ncol).each do |j|
          %td td#{j}

%h2 Source code
%ul
  %li
    %a{ href: "#{oss_url('app/views/bootstrap_examples/table.html.haml')}" } table.html.haml

%h2 References
%ul
  %li
    %a{ href: "https://v4-alpha.getbootstrap.com/content/tables/" } Bootstrap tables
  %li
    %a{ href: "https://codepen.io/gregor/pen/ApKxu" } Fixed 1st collumn table
  %li
    %a{ href: "https://codepen.io/tfzvang/pen/WQBwVo" } Fixed 1st header table

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse
  %button.navbar-toggler.navbar-toggler-right{ type: "button", "data-toggle": "collapse", "data-target": "#navbarSupportedContent", "aria-controls": "navbarSupportedContent", "aria-expanded": "false", "aria-label": "Toggle navigation" }
    %span.navbar-toggler-icon
  = link_to "Home", root_path, class: "navbar-brand"

  #navbarSupportedContent.collapse.navbar-collapse
    .navbar-nav.mr-auto
      =link_to 'Active', '#', class: "nav-item nav-link active"
      =link_to 'Link', '#', class: "nav-item nav-link"
      =link_to 'Disabled', '#', class: 'nav-item nav-link disabled'
      .nav-item.dropdown
        %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{ href:"#{root_path}", "data-toggle":"dropdown", "aria-haspopup":"true", "aria-expanded":"false" } Selection
        .dropdown-menu{ "aria-labelledby":"navbarDropdownMenuLink" }
          %a.dropdown-item{ href:"#{navbar_path}" } Navbar
          %a.dropdown-item{ href:"#{btn_path}" } Buttons
          %a.dropdown-item{ href: "#{grid_path}" } Grid
          %a.dropdown-item{ href: "#{table_path}" } Table
          %a.dropdown-item{ href: "#{tmp_path}" } Temporary
      %span.navbar-text
        %span Bootstrap4/Haml/Rails Example
    .navbar-nav
      %form.form-inline.my-2.my-lg-0
        %input.form-control.mr-sm-2{ type:"text", placeholder:"Search" }
        %button.btn.btn-outline-success.my-2.my-sm-0{ type:"submit" } Search

app/views/layouts/application.html.haml
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ "http-equiv": "X-UA-Compatible", content: "IE=edge" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    %title Bootstrap4/Rails
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container-fluid
      %header
        = render 'layouts/navigation'
      %main{:role => "main"}
        = yield